config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'categories#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :articles do
    resources :votes
  end
  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizes
  has_many :articles, through: :categorizes

  validates :name, presence: true, uniqueness: true, length: { in: 3..30 }
  validates :priority, presence: true, numericality: { only_integer: true }, uniqueness: {
    message: ': Sorry, there is already another category in this priority level.'
  }

  def self.ordered_priority
    all.includes(:articles).order('priority DESC')
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user, only: [:new]
  before_action :set_category, only: [:show]

  def index
    @categories = Category.ordered_priority
  end

  def home
    @categories = Category.ordered_priority.limit(4)
    @featured_article = Article.popular
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'You created a new category!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @articles = @category.articles.order('created_at DESC').includes(:author)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def background_check(var)
    url_for(var.articles.last.image) if var.articles.exists?
  end

  def home_title_check(var)
    if var.articles.exists?
      render 'categories/partials/has_title', cat: var
    else
      content_tag(:p, 'no articles', class: ['index-category-articles-count'])
    end
  end

  def article_count_check(var)
    if var.articles.exists?
      render 'categories/partials/has_article', category: var
    else
      content_tag(:p, 'no articles', class: ['index-category-articles-count'])
    end
  end

  def featured_article_check
    if @featured_article.blank?
      render 'categories/partials/featured_article_missing'
    else
      render 'categories/partials/featured_article_exists'
    end
  end
end

app/views/categories/partials/_featured_article_exists.html.erb
<div class="featured_article" style="background-image: url(<%= (url_for(@featured_article.image)) %>")>
  <div class="featured-article-gradient">
    <div class="info">
      <div class="feat-title">
        <%= link_to @featured_article.title, article_path(@featured_article) %>
      </div>
      <div class="feat-text">
        <%= @featured_article.text.truncate(300) %>
      </div>
    </div>
  </div>
</div>

app/views/categories/partials/_featured_article_missing.html.erb
<div class="no-featured-article">
  <h1>Welcome</h1>
  <h3>Looks like you are the first user or there are currently no any articles. Here is what you can do next.</h3>
  <ul>
    <li><%=link_to 'CREATE', new_category_path %> a new category.</li>
    <li>Give it a name a and priority number.</li>
    <li>Now you are ready to <%= link_to 'WRITE', new_article_path %> a new article </li>
    <li>You may write on any existing (if any) category too.</li>
  </ul>
</div>

app/views/categories/partials/_has_article.html.erb
<div class="index-category-articles-count">
  <%= pluralize(category.articles.size, 'article') %>
</div>

app/views/categories/partials/_has_title.html.erb
<div class="title-latest"><%= cat.articles.last.title %></div>