config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'categories#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :articles do
    resources :votes
  end
  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author, class_name: 'User'
  validates :title, presence: true

  has_one_attached :image
  validates :image, presence: true
  validate :accepted_image

  has_many :votes, dependent: :destroy

  has_many :categorizes
  has_many :categories, through: :categorizes, dependent: :destroy

  scope :popular, -> { order('votes_count DESC NULLS LAST').first }

  def accepted_image
    return unless image.attached?

    errors.add(:image, 'is too large (max 2MB)') unless image.byte_size <= 2.megabyte

    accepted_types = ['image/jpeg', 'image/jpg', 'image/png']
    errors.add(:image, 'must be a JPEG/JPG or PNG') unless accepted_types.include?(image.content_type)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :logged_in_user, only: %i[new update destroy]
  def index
    @articles = Article.all.order('created_at DESC')
  end

  def new
    @article = current_user.authored_articles.build
  end

  def create
    @article = current_user.authored_articles.build(article_params)
    @article.categorizes.build(category_id: params[:article][:category_ids])
    if @article.save
      flash[:notice] = 'Article created successfully!'
      redirect_to @article
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article edited successfully!'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = 'Article deleted successfully!'
      redirect_to articles_path
    else
      flash[:alert] = 'Something went wrong!'
      redirect_to @article
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :image)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def form_image_check(form)
    if @article.image.attached?
      render 'articles/partials/has_image', f: form
    else
      render 'articles/partials/has_no_image', f: form
    end
  end

  def show_image_check
    render 'articles/partials/show_image' if @article.image.attached?
  end

  def show_vote(var)
    vote = Vote.find_by(article: var, user: current_user)
    if vote
      render 'articles/partials/votedown', var: var, vote: vote
    else
      render 'articles/partials/voteup', var: var
    end
  end
end

app/views/articles/partials/_has_image.html.erb
<%= image_tag @article.image.variant(resize_to_limit: [100, 100]) %>
<%= f.label :image, 'Change this image?' %>

app/views/articles/partials/_has_no_image.html.erb
<%= f.label :image, 'Add a suitable image for your article' %>

app/views/articles/partials/_show_image.html.erb
<div class="">
  <%= image_tag @article.image.variant(resize_to_limit: [700, 700]) %>
</div>

app/views/articles/partials/_votedown.html.erb
<%= link_to article_vote_path(var.id, id: vote.id), method: :delete do %>
  <span><i class="fas fa-thumbs-down"></i></span>
<% end %>

app/views/articles/partials/_voteup.html.erb
<%= link_to article_votes_path(var), method: :post do %>
  <span><i class="fas fa-thumbs-up"></i></span>
<% end %>