config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'categories#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :articles do
    resources :votes
  end
  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizes
  has_many :articles, through: :categorizes

  validates :name, presence: true, uniqueness: true, length: { in: 3..30 }
  validates :priority, presence: true, numericality: { only_integer: true }, uniqueness: {
    message: ': Sorry, there is already another category in this priority level.'
  }

  def self.ordered_priority
    all.includes(:articles).order('priority DESC')
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user, only: [:new]
  before_action :set_category, only: [:show]

  def index
    @categories = Category.ordered_priority
  end

  def home
    @categories = Category.ordered_priority.limit(4)
    @featured_article = Article.popular
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'You created a new category!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @articles = @category.articles.order('created_at DESC').includes(:author)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def background_check(var)
    url_for(var.articles.last.image) if var.articles.exists?
  end

  def home_title_check(var)
    if var.articles.exists?
      render 'categories/partials/has_title', cat: var
    else
      content_tag(:p, 'no articles', class: ['index-category-articles-count'])
    end
  end

  def article_count_check(var)
    if var.articles.exists?
      render 'categories/partials/has_article', category: var
    else
      content_tag(:p, 'no articles', class: ['index-category-articles-count'])
    end
  end

  def featured_article_check
    if @featured_article.blank?
      render 'categories/partials/featured_article_missing'
    else
      render 'categories/partials/featured_article_exists'
    end
  end
end

app/views/categories/home.html.erb
<%= featured_article_check %>
<div class="categories">
  <% @categories.each do |cat| %>
    <div class="single-category" style="background-image: url(<%= background_check(cat) %>)">
      <div class="title-category"><%=link_to cat.name, category_path(cat) %></div>
      <%= home_title_check(cat) %>
    </div>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="index-category-container">
  <% @categories.each do |category| %>
    <div class="index-category-single" style="background-image: url(<%= background_check(category) %>)">
      <div class="index-category-name">
        <%= link_to category.name, category_path(category) %><br />
        <%= article_count_check(category) %>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<%= form_with(model: @category, local: true) do |f| %>
  <%= check_error(@category) %>
  <div class="new-category-form">
    <div class="new-category-input">
      <%= f.text_field :name, autofocus: true, placeholder: 'name' %>
    </div>
    <div class="new-category-input">
      <%= f.number_field :priority, placeholder: 'give it a priority number' %>
    </div>
    <div class="new-category-btn">
      <%= f.submit 'Submit', class: 'btn btn-submit' %>
      <%= link_to 'Cancel', :back, class: 'btn btn-cancel' %>
    </div>
  </div>
<% end %>

app/views/categories/show.html.erb
<div class="show-container">
  <% @articles.each do |art| %>
    <div class="show-article">
      <div class="show-article-image"style="background-image: url(<%= (url_for(art.image.variant(resize_to_fit: [490, nil]))) %>")></div>
      <div class="show-article-description">
        <div class="show-category-name">
          <%= art.categories.first.name %>
        </div>
        <div class="show-article-title">
          <%= link_to art.title, article_path(art) %>
        </div>
        <div class="show-article-text">
        <%= art.text.truncate(250) %>
        </div>
        <div class="article-vote">
          <div class="show-article-author">
            written by <strong><%= link_to art.author.name, user_path(art.author) %></strong>
          </div>
          <div class="show-article-vote">
            <%= show_vote(art) %>
            <%= pluralize(art.votes.count, 'vote') %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>