config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'categories#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :articles do
    resources :votes
  end
  resources :categories, except: [:destroy]
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-left">
    <%= image_tag 'logo-footer.png', class: 'nav-logo'%>
  </div>

  <div class="footer-center">
    <a href="#">Privacy Policy</a>
    <a href="#">Terms & Conditions</a>
    <p>Copyright 2020. All rights reserved.</p>
  </div>

  <div class="footer-right">
    <p>Connect with us:</p>
    <div id="social">
      <a class="twitterBtn smGlobalBtn" href="#" ></a>
			<a class="instagramBtn smGlobalBtn" href="#" ></a>
			<a class="facebookBtn smGlobalBtn" href="#" ></a>
		</div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar">
  <div class="nav-left">
    <div class="logo">
    <%= link_to root_path do %>
      <%= image_tag 'logo-new.png', class: 'nav-logo'%>
    <% end %>
    </div>
    <%= login_check_left %>
  </div>

  <div class="nav-center">
    <%= link_to 'home', root_path %>
    <% categ = Category.ordered_priority.limit(5) %>
    <% categ.each do |cat| %>
      <%= link_to cat.name, category_path(cat) %>
    <% end %>
    <%= link_to 'all categories', categories_path %>
  </div>

  <div class="nav-right">
    <%= login_check_right %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorCapstoneArticleTree</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/7d6392431b.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="flash flash-<%=message_type%>"><%= message %></div>
      <% end %>
      </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>